### ISSUE TITLE
New stark affiliate program section

### ISSUE THREAD

**Issue by Kevils** [starknet-id/affiliate.starknet.id#20]
## Description 📹

Loom: [https://www.loom.com/share/036e8ad7ead349b188733c768ee23479](https://www.loom.com/share/036e8ad7ead349b188733c768ee23479)

We've refactored the Stark affiliate program to have something more clear & straightforward. This section allows users to copy their referral link for sharing.

Old section: [https://affiliate.starknet.id/](https://affiliate.starknet.id/)  
![image](https://github.com/user-attachments/assets/ba881c26-52e8-4242-9ab8-c214367bdc3f)

New section:  
[https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1](https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1)  
![image](https://github.com/user-attachments/assets/54979d9b-c824-4bff-8455-8a19003f3b88)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by snehaa-eth** [comment]
Hey can i work on this? i have experience of full stack eta max 2 hours

**Comment by vestor-dev** [comment]
Can I hop on this

**Comment by Emmanex01** [comment]
May I pick this up?

**Comment by Benjtalkshow** [comment]
Could I be assigned to this?

**Comment by wheval** [comment]
Hello, Can i work on this. I have gone through the video and I can get this done quickly. Please assign.
ETA is 5 hours. Thanks

**Comment by Michaelkingsdev** [comment]
Let me handle this issue!
