### ISSUE TITLE
New unclaimed revenue & marketing toolkip section

### ISSUE THREAD

**Issue by Kevils** [starknet-id/affiliate.starknet.id#21]
## Description 📹

Loom: [https://www.loom.com/share/3c54149a25264710a0ad8c926bc1b07a](https://www.loom.com/share/3c54149a25264710a0ad8c926bc1b07a)

There are two new cards: one for claiming earnings (if the user has any) and another to download the Starknet ID toolkit for marketing. Add tooltip also by hovering the icon info.

Current section:  
![image](https://github.com/user-attachments/assets/eb5609f6-aa06-47a8-afed-4419ac103451)  
![image](https://github.com/user-attachments/assets/e0003fef-32f1-4fca-8e91-30d30370fa62)

New section:  
[https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1](https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1)  
![image](https://github.com/user-attachments/assets/f4578480-e082-407d-81b0-7351abfdc2cb)

## Proposed Actions 🛠️

Here's a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   [Propose the changes you would like to see in the code]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren't assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by vestor-dev** [comment]
Hey @Kevils I'm new and would like to hop on this one

**Comment by Emmanex01** [comment]
Can I try solving this issue?

**Comment by wheval** [comment]
Hello, can i work on this. I would love to contribute.

**Comment by Favvie** [comment]
I'd love to give this a go.

My name is Favour Abangwu, a Software Engineer with experience using ReactJS/NextJS with TypeScript/JavaScript.  I have solid experience in implementing pixel-perfect, responsive screens and delivering high-quality front-end solutions. If assigned this issue, I am confident in tackling this issue and I will send my first PR within 48 hrs.

Thank you!

**Comment by 0xdevcollins** [comment]
I’m interested in this one.

**Comment by mimisavage** [comment]
Could I be assigned to this?

**Comment by suhas-sensei** [comment]
Can I work on this, please? would love to contribute.

**Comment by OWK50GA** [comment]
Hi, I am Wilfrid, a Frontend Web Developer and I will like to work on this. 
I will open find which page(s) and which file(s) are responsible for the Claim Earnings and Download Marketing Toolkit.
I am already familiar by sight with the custom styles defined in your project that I would need to apply to get the cards as shown.
I will like to take this issue

**Comment by Khemmie-Ray** [comment]
Hello, can i work on this?
