### ISSUE TITLE
Refont of FAQ section

### ISSUE THREAD

**Issue by Kevils** [starknet-id/affiliate.starknet.id#22]
## Description 📹

Loom: [https://www.loom.com/share/ff249906156e4977b17c70e74f256325](https://www.loom.com/share/ff249906156e4977b17c70e74f256325)

We made various design-only adjustments to the FAQ section, but the functionality remains the same. We placed the title at the top and added a subtitle. We also adjusted the text size, changed the divider color, and reduced the padding.

Old section:  
![image](https://github.com/user-attachments/assets/a02b50b4-37a1-4487-82b6-9ae5f498ee6a)

New section:  
[https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1](https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1)  
![image](https://github.com/user-attachments/assets/8edbc13c-90cd-4b34-982f-302815aab862)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by martinvibes** [comment]
Hey @Kevils can I hop on this one

**Comment by petersdt** [comment]
@Kevils @fricoben kindly assign me this issue would love to contribute to the starkquest eco system

**Comment by SudiptaPaul-31** [comment]
Can I get this issue assigned?

MY workflow:

First will start inspecting the FAQ section on the codebase and understand its css properites like fontsize and other necessary  and then making changes as per the requested changes and moreover its responsive on every devices and ten at last testing it and finally making a PR.

ETA=24hours

**Comment by Emmanex01** [comment]
Can I try solving this issue?

**Comment by Michaelkingsdev** [comment]
Mind if I take this issue?
