### ISSUE TITLE
Change fonts and navbar UI

### ISSUE THREAD

**Issue by fricoben** [starknet-id/affiliate.starknet.id#23]
## Description 📹

This app wasn't updated for a while and the UI seems different than the app.starknet.id one on the menu/front and connection button. I want you to update to use the same UI as our app.

What we have
<img width="411" alt="Capture d’écran 2024-11-15 à 09 55 05" src="https://github.com/user-attachments/assets/75f6b32e-5b7f-402c-8934-1be7c50c1076">

What we want
<img width="600" alt="Capture d’écran 2024-11-15 à 09 55 13" src="https://github.com/user-attachments/assets/b93d0c5f-7115-4d97-b817-14b471517409">

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	
- [ ] Change font-weight of menu items to make it match (delete bold property)
- [ ] Add the quickzap font on button

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Villarley** [comment]
Hi @fricoben,
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I have contributed before to lfglabs projects, so I do understand how the team works and I'm looking forward to keep contributing my best to the project!!!

**Comment by vestor-dev** [comment]
Can I handle this issue @Kevils I'm new to this repo this seems good for a newcomer like myself

**Comment by Joe-joe25** [comment]
@fricoben kindly assign me this task i would like to make it my first contribution to the starkquest project

**Comment by CollinsC1O** [comment]
Hello @fricoben I'm a front-end and a blockchain developer. I will love to take on this and get it done

**Comment by SudiptaPaul-31** [comment]
@fricoben Can I tackle this issue

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue:

My approach:
Will start by inspecting the navbar and get the proper sizing and then finding it on the codebase and making changes as per requested.
Enabling that it is responsive in every screens and at last testing it before making a PR.

ETA-2Days

**Comment by OWK50GA** [comment]
May I take this issue on?
I'm a Frontend Web Developer and I can handle this issue

**Comment by Emmanex01** [comment]
Could I take over this issue?
Well experience in frontend

**Comment by Benjtalkshow** [comment]
Could I take a shot at this?

**Comment by lauchaves** [comment]
Is it okay if I tackle this? I'm a member of dojo coding. I have a lot of experience in frontend Id make sure it looks consistent with the rest of the app!

**Comment by Michaelkingsdev** [comment]
I'd love to work on this!

**Comment by lauchaves** [comment]
Hey @fricoben this is ready for review! 🚀
