### ISSUE TITLE
Make our `404.tsx` page consistent over our apps

### ISSUE THREAD

**Issue by fricoben** [starknet-id/affiliate.starknet.id#25]
## Description 📹

We want to make our `404.tsx` page consistent over our apps. This means we need to change [our 404.tsx page in this repo](https://github.com/lfglabs-dev/affiliate.starknet.id/blob/testnet/pages/404.tsx) to make it match [the app.starknet.id one](https://github.com/lfglabs-dev/app.starknet.id/blob/testnet/pages/404.tsx).

The only difference is that instead of using the `errorIllu.webp` you can use the `404illu.web` you'll find attached to this issue.

[404.zip](https://github.com/user-attachments/files/17764093/404.zip)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
- [ ] Refactor 404 page to make it similar [to this one](https://github.com/lfglabs-dev/app.starknet.id/blob/testnet/pages/404.tsx)
- [ ] Make sure the content is centered and give the same experience as here https://app.starknet.id/404example

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by martinvibes** [comment]
Hey @Kevils would like to hop on this one

**Comment by mayasimi** [comment]
@fricoben can i be assigned this issue

**Comment by Emmanex01** [comment]
Can I take care of this issue?

**Comment by OWK50GA** [comment]
Can I try solving this issue?
I'm a Frontend Web Developer and I can handle this issue with the 404example reference given

**Comment by Benjtalkshow** [comment]
Could I be assigned to this?

**Comment by Michaelkingsdev** [comment]
Could I take a shot at this?
