### ISSUE TITLE
Make our `error.tsx` page consistent

### ISSUE THREAD

**Issue by fricoben** [starknet-id/affiliate.starknet.id#26]
## Description 📹

[The error.tsx page 
](https://github.com/lfglabs-dev/affiliate.starknet.id/blob/testnet/pages/error.tsx) used for asking the user to connect isn't the best right now and we want to add an image to it to illustrate the problem better. Just add [this image](https://github.com/lfglabs-dev/app.starknet.id/blob/testnet/public/visuals/errorIllu.webp) as webp to the component (and in the right folder).

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Villarley** [comment]
Hi @fricoben 
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features. I already contributed, so I would be able to deliver faster. I'm looking forward to keep contributing this project.

**Comment by Chukwuemeka-James** [comment]
@fricoben kindly assign me this task. It would be nice to make it my first contribution to the starkquest project.

**Comment by SudiptaPaul-31** [comment]
@fricoben Can I work on this issue?

**Comment by Emmanex01** [comment]
Could I be assigned to this?

**Comment by OWK50GA** [comment]
I'd love to give this a go.
I'm a Frontend Web Developer and I can handle this. It's a simple addition of an image.

**Comment by Benjtalkshow** [comment]
May I try my hand at this?

**Comment by Michaelkingsdev** [comment]
Let me handle this issue!
